//----------GET PRODUCTS-------------
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

//-----GET TRL----------
export const FETCH_TRL_START = 'FETCH_TRL_START';
export const FETCH_TRL_SUCCESS = 'FETCH_TRL_SUCCESS';
export const FETCH_TRL_FAILURE = 'FETCH_TRL_FAILURE';
